# Generated by Django 4.2.28 on 2026-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_report_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('workspace_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_id', 'date'], name='transaction_user_id_059bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user_id', 'type'], name='transaction_user_id_7b4347_idx'),
        ),
    ]
