import os
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.units import inch

def generate_monthly_report_pdf(user_name, year, month, total_income, total_expenses, transactions, profile_photo_path=None):
    """
    Generates a professional financial report in PDF format.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor("#374b91"),
        alignment=1,
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'HeadingStyle',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor("#2dd4bf"),
        spaceBefore=12,
        spaceAfter=12
    )

    elements = []

    # Logo/Header
    elements.append(Paragraph("FinTrack Monthly Report", title_style))
    
    # Profile Info
    month_name = datetime(year, month, 1).strftime("%B")
    info_text = f"<b>Client:</b> {user_name}<br/><b>Reporting Period:</b> {month_name} {year}<br/><b>Status:</b> Official"
    elements.append(Paragraph(info_text, styles["Normal"]))
    
    if profile_photo_path and os.path.exists(profile_photo_path):
        try:
            img = Image(profile_photo_path, width=1*inch, height=1*inch)
            img.hAlign = 'RIGHT'
            elements.append(img)
        except:
            pass
            
    elements.append(Spacer(1, 20))

    # Summary Cards Logic (as a table)
    summary_data = [
        ["Metric", "Value"],
        ["Total Income", f"${total_income:,.2f}"],
        ["Total Expenses", f"${total_expenses:,.2f}"],
        ["Net Savings", f"${(total_income - total_expenses):,.2f}"],
        ["Savings Rate", f"{((total_income - total_expenses) / total_income * 100 if total_income > 0 else 0):.1f}%"]
    ]
    
    summary_table = Table(summary_data, colWidths=[2*inch, 2*inch])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#374b91")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 30))

    # Transaction Table
    elements.append(Paragraph("Detailed Transactions", heading_style))
    
    txn_data = [["Date", "Category", "Type", "Amount"]]
    for tx in transactions[:20]: # Limit for summary, full reports could span pages
        txn_data.append([
            tx.date.strftime("%Y-%m-%d"),
            tx.category if hasattr(tx, 'category') else tx.type,
            "Income" if hasattr(tx, 'type') and tx.type != 'EXPENSE' else "Expense",
            f"${tx.amount:,.2f}"
        ])
        
    if not transactions:
        txn_data.append(["No records", "-", "-", "-"])

    txn_table = Table(txn_data, colWidths=[1.2*inch, 2*inch, 1*inch, 1.2*inch])
    txn_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f8fafc")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#64748b")),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('INNERGRID', (0, 0), (-1, -1), 0.25, colors.grey),
        ('BOX', (0, 0), (-1, -1), 0.25, colors.grey),
    ]))
    elements.append(txn_table)

    # Footer
    elements.append(Spacer(1, 50))
    footer_text = "Generated by FinTrack System. All rights reserved."
    elements.append(Paragraph(footer_text, styles["Italic"]))

    doc.build(elements)
    buffer.seek(0)
    return buffer
