
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'ht';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => any;
}

const translations = {
    fr: {
        dashboard: "Tableau de Bord",
        expenses: "Dépenses",
        income: "Revenus",
        search: "Recherche",
        settings: "Paramètres",
        logout: "Déconnexion",
        financial_pulse: "Pouls Financier",
        total_income: "Rentrées Totales",
        total_expenses: "Dépenses Totales",
        net_result: "Résultat Net",
        export_pdf: "Exporter PDF",
        add_expense: "Ajouter une Dépense",
        add_income: "Ajouter un Revenu",
        category: "Catégorie",
        amount: "Montant",
        date: "Date",
        comments: "Commentaires",
        save: "Enregistrer",
        cancel: "Annuler",
        sign_in: "Se Connecter",
        create_account: "Créer un Compte",
        welcome: "Bienvenue",
        language: "Langue",
        theme: "Thème",
        dark_mode: "Mode Sombre",
        light_mode: "Mode Clair",
        financial_overview: "Aperçu Financier",
        evolution_12_months: "Évolution des 12 derniers mois",
        growth_trend: "Tendance de Croissance",
        income_vs_expense: "Performance Revenus vs Dépenses",
        distribution: "Distribution",
        expense_allocation: "Répartition des dépenses",
        vs_target: "vs objectif",
        vs_last_week: "vs semaine dernière",
        bottom_line: "Résultat Net",
        incoming: "Rentrées",
        outcoming: "Sorties",
        higher: "plus élevé",
        lower: "plus bas",
        financial_reports: "Rapports Financiers",
        financial_reports_desc: "Générez et téléchargez des rapports mensuels détaillés.",
        report_settings: "Paramètres du rapport",
        month: "Mois",
        year: "Année",
        generating: "Génération en cours...",
        download_pdf: "Télécharger le PDF",
        complete_reports: "Rapports Complets",
        reports_desc_long: "Les rapports PDF incluent un résumé financier, la liste des transactions, le calcul des marges et les commissions vendeurs pour la période sélectionnée.",
        format: "Format",
        security: "Sécurité",
        encrypted: "Crypté",
        error_generating_report: "Impossible de générer le rapport. Veuillez réessayer.",
        months: ["Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre"],
        workspaces: "Espaces",
        dynamic_expenses: "Dépenses Dynamiques",
        form_builder: "Générateur de Formulaire",
        user_management: "Gestion des Utilisateurs",
        vendors: "Vendeurs",
        reports: "Rapports",
        manage_vendors_desc: "Gérer les vendeurs externes et les commissions.",
        add_vendor: "Ajouter un Vendeur",
        new_vendor: "Nouveau Vendeur",
        name: "Nom",
        vendor_name_placeholder: "Nom du vendeur",
        commission_rate: "Taux de Commission (%)",
        description: "Description",
        description_placeholder: "Description optionnelle...",
        saving: "Enregistrement...",
        create_vendor_btn: "Créer le Vendeur",
        delete: "Supprimer",
        rate: "Taux",
        total_paid: "Total Payé",
        no_vendors: "Aucun vendeur trouvé",
        confirm_delete_vendor: "Êtes-vous sûr de vouloir supprimer ce vendeur ?",
        name_required: "Le nom est requis",
        vendor_created: "Vendeur créé avec succès !",
        vendor_create_failed: "Échec de la création du vendeur",
        manage_workspaces_desc: "Gérez vos environnements d'entreprise",
        create_new_workspace: "Créer Nouveau",
        workspace_name_placeholder: "Nom de l'espace",
        add_workspace: "Ajouter l'Espace",
        active_environment: "Environnement Actif",
        failed_fetch_workspaces: "Échec du chargement des espaces",
        failed_create_workspace: "Échec de la création de l'espace",
        failed_delete_workspace: "Échec de la suppression de l'espace",
        confirm_delete_workspace: "Êtes-vous sûr de vouloir supprimer cet espace ?",
        select_form_desc: "Sélectionnez un formulaire pour commencer",
        new_entry: "Nouveau",
        select_option: "Sélectionner une option",
        submitting: "Envoi en cours...",
        save_entry: "Enregistrer l'Entrée",
        recent_entries: "Entrées Récentes",
        recent_activity: "Activité Récente",
        no_entries_yet: "Aucune entrée pour le moment",
        configure_flow: "Configurez votre Flux",
        configure_flow_desc: "Sélectionnez l'un de vos formulaires de dépenses personnalisés ci-dessus pour commencer.",
        offline_error: "Vous êtes hors ligne. Veuillez vous connecter à Internet pour enregistrer une entrée.",
        account_pending: "Votre compte est en attente d'approbation par un administrateur.",
        entry_save_error: "Erreur lors de l'enregistrement de la dépense.",
        confirm_delete_entry: "Supprimer cette entrée ?",
        delete_error: "Erreur lors de la suppression.",
        create_new: "Créer Nouveau",
    },
    en: {
        dashboard: "Dashboard",
        expenses: "Expenses",
        income: "Income",
        search: "Search",
        settings: "Settings",
        logout: "Logout",
        financial_pulse: "Financial Pulse",
        total_income: "Total Income",
        total_expenses: "Total Expenses",
        net_result: "Net Result",
        export_pdf: "Export PDF",
        add_expense: "Add Expense",
        add_income: "Add Income",
        category: "Category",
        amount: "Amount",
        date: "Date",
        comments: "Comments",
        save: "Save",
        cancel: "Cancel",
        sign_in: "Sign In",
        create_account: "Create Account",
        welcome: "Welcome",
        language: "Language",
        theme: "Theme",
        dark_mode: "Dark Mode",
        light_mode: "Light Mode",
        financial_overview: "Financial Overview",
        evolution_12_months: "Evolution over last 12 months",
        growth_trend: "Growth Trend",
        income_vs_expense: "Income vs Expenses Performance",
        distribution: "Distribution",
        expense_allocation: "Expense Allocation",
        vs_target: "vs target",
        vs_last_week: "vs last week",
        bottom_line: "Bottom Line",
        incoming: "Incoming",
        outcoming: "Outcoming",
        higher: "higher",
        financial_reports: "Financial Reports",
        financial_reports_desc: "Generate and download detailed monthly reports.",
        report_settings: "Report Settings",
        month: "Month",
        year: "Year",
        generating: "Generating...",
        download_pdf: "Download PDF",
        complete_reports: "Complete Reports",
        reports_desc_long: "PDF reports include a financial summary, transaction list, margin calculation, and vendor commissions for the selected period.",
        format: "Format",
        security: "Security",
        encrypted: "Encrypted",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        workspaces: "Workspaces",
        dynamic_expenses: "Dynamic Expenses",
        form_builder: "Form Builder",
        user_management: "User Management",
        vendors: "Vendors",
        reports: "Reports",
        manage_vendors_desc: "Manage external vendors and commissions.",
        add_vendor: "Add Vendor",
        new_vendor: "New Vendor",
        name: "Name",
        vendor_name_placeholder: "Vendor Name",
        commission_rate: "Commission Rate (%)",
        description: "Description",
        description_placeholder: "Optional description...",
        saving: "Saving...",
        create_vendor_btn: "Create Vendor",
        delete: "Delete",
        rate: "Rate",
        total_paid: "Total Paid",
        no_vendors: "No vendors found",
        confirm_delete_vendor: "Are you sure you want to delete this vendor?",
        name_required: "Name is required",
        vendor_created: "Vendor created successfully!",
        vendor_create_failed: "Failed to create vendor",
        manage_workspaces_desc: "Manage your corporate environments",
        create_new_workspace: "Create New",
        workspace_name_placeholder: "Workspace Name",
        add_workspace: "Add Workspace",
        active_environment: "Active Environment",
        failed_fetch_workspaces: "Failed to load workspaces",
        failed_create_workspace: "Failed to create workspace",
        failed_delete_workspace: "Failed to delete workspace",
        confirm_delete_workspace: "Are you sure you want to delete this workspace?",
        select_form_desc: "Select a form to begin entry",
        new_entry: "New",
        select_option: "Select option",
        submitting: "Submitting...",
        save_entry: "Save Entry",
        recent_entries: "Recent Entries",
        recent_activity: "Recent Activity",
        no_entries_yet: "No entries yet",
        configure_flow: "Configure Your Flow",
        configure_flow_desc: "Select one of your custom expense forms from the list above to start logging data.",
        offline_error: "You are offline. Please connect to the internet to save an entry.",
        account_pending: "Your account is pending approval by an administrator.",
        entry_save_error: "Error saving expense entry.",
        confirm_delete_entry: "Delete this entry?",
        delete_error: "Error deleting entry.",
        create_new: "Create New",
    },
    ht: {
        dashboard: "Tablo de Bò",
        expenses: "Depans",
        income: "Revenn",
        search: "Chèche",
        settings: "Paramèt",
        logout: "Dekonekte",
        financial_pulse: "Pous Finansye",
        total_income: "Total Lajan Antre",
        total_expenses: "Total Depans",
        net_result: "Rezilta Nèt",
        export_pdf: "Ekspòte PDF",
        add_expense: "Ajoute yon Depans",
        add_income: "Ajoute yon Revenn",
        category: "Kategori",
        amount: "Montan",
        date: "Dat",
        comments: "Kòmantè",
        save: "Anrejistre",
        cancel: "Anile",
        sign_in: "Konekte",
        create_account: "Kreye yon Kont",
        welcome: "Byenvini",
        language: "Lang",
        theme: "Tèm",
        dark_mode: "Mòd Nwa",
        light_mode: "Mòd Klè",
        financial_overview: "Apèsi Finansye",
        evolution_12_months: "Evolisyon 12 dènye mwa yo",
        growth_trend: "Tandans Kwasans",
        income_vs_expense: "Pèfòmans Revenn vs Depans",
        distribution: "Distribisyon",
        expense_allocation: "Repatisyon Depans",
        vs_target: "vs objektif",
        vs_last_week: "vs semèn pase",
        bottom_line: "Rezilta Nèt",
        incoming: "Lajan Antre",
        outcoming: "Lajan Sòti",
        higher: "pi wo",
        financial_reports: "Rapò Finansye",
        financial_reports_desc: "Jenere ak telechaje rapò mansyèl detaye.",
        report_settings: "Paramèt Rapò",
        month: "Mwa",
        year: "Ane",
        generating: "Jenerasyon an kou...",
        download_pdf: "Telechaje PDF",
        complete_reports: "Rapò Konplè",
        reports_desc_long: "Rapò PDF yo gen ladan yon rezime finansye, lis tranzaksyon, kalkil maj, ak komisyon vandè pou peryòd chwazi a.",
        format: "Fòma",
        security: "Sekirite",
        encrypted: "Kripte",
        months: ["Janvye", "Fevriye", "Mas", "Avril", "Me", "Jen", "Jiyè", "Out", "Septanm", "Oktòb", "Novanm", "Desanm"],
        workspaces: "Espace Travay",
        dynamic_expenses: "Depans Dinamik",
        form_builder: "Kreyatè Fòm",
        user_management: "Jesyon Itilizatè",
        vendors: "Vandè",
        reports: "Rapò",
        manage_vendors_desc: "Jere vandè ekstèn ak komisyon.",
        add_vendor: "Ajoute Vandè",
        new_vendor: "Nouvo Vandè",
        name: "Non",
        vendor_name_placeholder: "Non vandè a",
        commission_rate: "To Komisyon (%)",
        description: "Deskripsyon",
        description_placeholder: "Deskripsyon si ou vle...",
        saving: "Ap anrejistre...",
        create_vendor_btn: "Kreye Vandè",
        delete: "Efase",
        rate: "To",
        total_paid: "Total Peye",
        no_vendors: "Pa jwenn okenn vandè",
        confirm_delete_vendor: "Èske ou sèten ou vle efase vandè sa a?",
        name_required: "Non obligatwa",
        vendor_created: "Vandè kreye avèk siksè!",
        vendor_create_failed: "Echèk nan kreyasyon vandè",
        manage_workspaces_desc: "Jere anviwònman antrepriz ou yo",
        create_new_workspace: "Kreye Nouvo",
        workspace_name_placeholder: "Non Espace la",
        add_workspace: "Ajoute Espace",
        active_environment: "Anviwònman Aktif",
        failed_fetch_workspaces: "Echèk nan chaje espas yo",
        failed_create_workspace: "Echèk nan kreyasyon espas la",
        failed_delete_workspace: "Echèk nan sipresyon espas la",
        confirm_delete_workspace: "Èske ou sèten ou vle efase espas sa a?",
        select_form_desc: "Chwazi yon fòmilè pou kòmanse",
        new_entry: "Nouvo",
        select_option: "Chwazi yon opsyon",
        submitting: "Ap voye...",
        save_entry: "Anrejistre",
        recent_entries: "Entrée Resan",
        recent_activity: "Aktivite Resan",
        no_entries_yet: "Pa gen okenn entrée ankò",
        configure_flow: "Konfigire Flux ou",
        configure_flow_desc: "Chwazi youn nan fòmilè depans pèsonalize ou yo anwo a pou kòmanse.",
        offline_error: "Ou pa gen entènèt. Tanpri konekte sou entènèt pou anrejistre.",
        account_pending: "Kont ou an ap tann apwobasyon yon administratè.",
        entry_save_error: "Erè nan anrejistreman depans la.",
        confirm_delete_entry: "Efase entrée sa a?",
        delete_error: "Erè nan sipresyon.",
        create_new: "Kreye Nouvo",
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('language');
        return (saved as Language) || 'fr';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string) => {
        const keys = key.split('.');
        let result: any = translations[language];
        for (const k of keys) {
            if (result[k]) result = result[k];
            else return key;
        }
        return result;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
